import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  ActivityIndicator,
  TouchableOpacity,
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import axios from 'axios';
import { Ionicons } from '@expo/vector-icons';

const BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL;

interface Prediction {
  prediction_id: string;
  game_id: string;
  home_team: string;
  away_team: string;
  predicted_home_score: number;
  predicted_away_score: number;
  moneyline_pick: string;
  spread_pick: string;
  spread_value: number;
  total_pick: string;
  total_value: number;
  confidence: number;
  consensus_article: string;
}

export default function GameDetailScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams();
  const [prediction, setPrediction] = useState<Prediction | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPrediction = async () => {
      try {
        const response = await axios.get(`${BACKEND_URL}/api/games/${id}`, {
          withCredentials: true,
        });
        setPrediction(response.data);
      } catch (error) {
        console.error('Error fetching prediction:', error);
      } finally {
        setLoading(false);
      }
    };

    if (id) {
      fetchPrediction();
    }
  }, [id]);

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#ff6b35" />
      </View>
    );
  }

  if (!prediction) {
    return (
      <View style={styles.container}>
        <Text style={styles.errorText}>Prediction not found</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backButton} onPress={() => router.back()}>
          <Ionicons name="arrow-back" size={24} color="#fff" />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Game Prediction</Text>
      </View>

      <View style={styles.matchup}>
        <View style={styles.teamContainer}>
          <Text style={styles.teamName}>{prediction.away_team}</Text>
          <Text style={styles.predictedScore}>{prediction.predicted_away_score.toFixed(1)}</Text>
        </View>
        <Text style={styles.vs}>@</Text>
        <View style={styles.teamContainer}>
          <Text style={styles.teamName}>{prediction.home_team}</Text>
          <Text style={styles.predictedScore}>{prediction.predicted_home_score.toFixed(1)}</Text>
        </View>
      </View>

      <View style={styles.confidenceSection}>
        <Text style={styles.confidenceLabel}>Confidence Level</Text>
        <View style={styles.confidenceBar}>
          <View style={[styles.confidenceFill, { width: `${prediction.confidence}%` }]} />
        </View>
        <Text style={styles.confidenceText}>{prediction.confidence.toFixed(0)}%</Text>
      </View>

      <View style={styles.picksSection}>
        <Text style={styles.sectionTitle}>Betting Picks</Text>
        
        <View style={styles.pickCard}>
          <View style={styles.pickHeader}>
            <Ionicons name="cash" size={24} color="#ff6b35" />
            <Text style={styles.pickTitle}>Moneyline</Text>
          </View>
          <Text style={styles.pickValue}>{prediction.moneyline_pick}</Text>
        </View>

        <View style={styles.pickCard}>
          <View style={styles.pickHeader}>
            <Ionicons name="swap-horizontal" size={24} color="#ff6b35" />
            <Text style={styles.pickTitle}>Spread</Text>
          </View>
          <Text style={styles.pickValue}>{prediction.spread_pick}</Text>
          <Text style={styles.pickDetail}>Line: {prediction.spread_value > 0 ? '+' : ''}{prediction.spread_value.toFixed(1)}</Text>
        </View>

        <View style={styles.pickCard}>
          <View style={styles.pickHeader}>
            <Ionicons name="trending-up" size={24} color="#ff6b35" />
            <Text style={styles.pickTitle}>Total</Text>
          </View>
          <Text style={styles.pickValue}>{prediction.total_pick} {prediction.total_value.toFixed(1)}</Text>
          <Text style={styles.pickDetail}>Predicted total: {(prediction.predicted_home_score + prediction.predicted_away_score).toFixed(1)}</Text>
        </View>
      </View>

      <View style={styles.articleSection}>
        <Text style={styles.sectionTitle}>Consensus Analysis</Text>
        <View style={styles.articleCard}>
          <Text style={styles.articleText}>{prediction.consensus_article}</Text>
        </View>
      </View>

      <View style={styles.disclaimer}>
        <Ionicons name="information-circle" size={20} color="#808080" />
        <Text style={styles.disclaimerText}>
          This prediction is generated by AI and should be used for informational purposes only. Always gamble responsibly.
        </Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1a1a2e',
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#1a1a2e',
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingTop: 48,
  },
  backButton: {
    padding: 8,
    marginRight: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  matchup: {
    padding: 24,
    alignItems: 'center',
  },
  teamContainer: {
    alignItems: 'center',
    marginVertical: 8,
  },
  teamName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
  },
  predictedScore: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#ff6b35',
  },
  vs: {
    fontSize: 16,
    color: '#a0a0a0',
    marginVertical: 8,
  },
  confidenceSection: {
    padding: 24,
    alignItems: 'center',
  },
  confidenceLabel: {
    fontSize: 16,
    color: '#a0a0a0',
    marginBottom: 12,
  },
  confidenceBar: {
    width: '100%',
    height: 32,
    backgroundColor: '#16213e',
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 8,
  },
  confidenceFill: {
    height: '100%',
    backgroundColor: '#ff6b35',
  },
  confidenceText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  picksSection: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 16,
  },
  pickCard: {
    backgroundColor: '#16213e',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#0f3460',
  },
  pickHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  pickTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#a0a0a0',
    marginLeft: 8,
  },
  pickValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 4,
  },
  pickDetail: {
    fontSize: 14,
    color: '#a0a0a0',
  },
  articleSection: {
    padding: 16,
  },
  articleCard: {
    backgroundColor: '#16213e',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#0f3460',
  },
  articleText: {
    fontSize: 15,
    color: '#c0c0c0',
    lineHeight: 24,
  },
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 24,
    paddingBottom: 32,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#808080',
    marginLeft: 8,
    flex: 1,
    lineHeight: 18,
  },
  errorText: {
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
    marginTop: 48,
  },
});
